import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, Bell, BookOpen, CalendarDays, Check, ChevronDown, File, FileText, FolderOpen, LayoutDashboard, ListFilter, MessageCircle, MoreHorizontal, PanelLeftClose, Plus, Search, SlidersHorizontal, Sparkles, UploadCloud, Users, X } from 'lucide-react';
import { parseProjectFile, type ImportedTask } from './importProject';
import { summerComments, summerKnowledge, summerMaterials } from './summerCampData';
import mammoth from 'mammoth/mammoth.browser';

type Task=ImportedTask;
type Knowledge={title:string;icon:string;items:string[]};
type Material={title:string;group:string;url?:string;note:string;fileName?:string};
type Project={id:string;name:string;emoji:string;description:string;tasks:Task[];knowledge:Knowledge[];materials:Material[];comments:{author:string;text:string;anchor:string}[]};

const initialTasks:Task[]=[
 {id:1,title:'Сформировать концепцию лагеря',stage:'Концепция',color:'#7557ed',start:0,span:4,owner:'Анна Морозова',initials:'АМ',status:'Готово',progress:100},
 {id:2,title:'Подготовить тексты лендинга',stage:'Тексты',color:'#f2b938',start:2,span:5,owner:'Саша Волков',initials:'СВ',status:'В работе',progress:64},
 {id:3,title:'Визуальная концепция',stage:'Дизайн',color:'#ff6e73',start:4,span:5,owner:'Маша Ким',initials:'МК',status:'В работе',progress:38},
 {id:4,title:'Дизайн лендинга',stage:'Дизайн',color:'#ff6e73',start:7,span:6,owner:'Маша Ким',initials:'МК',status:'Не начато',progress:0},
 {id:5,title:'Разработка лендинга',stage:'Разработка',color:'#4f8df7',start:11,span:7,owner:'Илья Левин',initials:'ИЛ',status:'Не начато',progress:0},
 {id:6,title:'Подготовить PR-материалы',stage:'PR',color:'#a564e8',start:13,span:5,owner:'Лера Новик',initials:'ЛН',status:'Не начато',progress:0},
 {id:7,title:'Тестирование и запуск',stage:'Запуск',color:'#25b884',start:18,span:5,owner:'Илья Левин',initials:'ИЛ',status:'Не начато',progress:0},
];
const starter:Project={id:'summer-camp',name:'Summer Camp',emoji:'🏕️',description:'Летний спецпроект Blink · август 2026',tasks:initialTasks,knowledge:summerKnowledge,materials:summerMaterials,comments:summerComments};
const days=Array.from({length:23},(_,i)=>({d:i+8,w:['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][i%7]}));

export function App(){
 const [projects,setProjects]=useState<Project[]>(()=>{try{return JSON.parse(localStorage.getItem('blink-projects')||'null')||[starter]}catch{return[starter]}});const [projectId,setProjectId]=useState(()=>localStorage.getItem('blink-active-project')||starter.id);const [section,setSection]=useState<'Гант'|'База знаний'|'Материалы'>('Гант');const [query,setQuery]=useState('');const [sidebar,setSidebar]=useState(true);const [newProject,setNewProject]=useState(false);const [projectName,setProjectName]=useState('');const [importing,setImporting]=useState(false);const [message,setMessage]=useState('');const [active,setActive]=useState<Task|null>(null);const ganttInput=useRef<HTMLInputElement>(null);const briefInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{localStorage.setItem('blink-projects',JSON.stringify(projects))},[projects]);useEffect(()=>{localStorage.setItem('blink-active-project',projectId)},[projectId]);
 const project=projects.find(x=>x.id===projectId)||projects[0];const update=(patch:Partial<Project>)=>setProjects(all=>all.map(item=>item.id===project.id?{...item,...patch}:item));
 const filtered=useMemo(()=>project.tasks.filter(t=>(t.title+t.owner+t.stage).toLowerCase().includes(query.toLowerCase())),[project.tasks,query]);
 const importGantt=async(file?:File)=>{if(!file)return;setImporting(true);setMessage('');try{const tasks=await parseProjectFile(file);update({tasks});setSection('Гант');setMessage(`Гант загружен · ${tasks.length} задач`)}catch(error){setMessage(error instanceof Error?error.message:'Не удалось прочитать файл')}finally{setImporting(false);if(ganttInput.current)ganttInput.current.value=''}};
 const importBrief=async(file?:File)=>{if(!file)return;setImporting(true);setMessage('');try{let text='';if(/\.(txt|md|csv|json)$/i.test(file.name))text=await file.text();if(/\.docx$/i.test(file.name))text=(await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value;const item:Material={title:file.name.replace(/\.[^.]+$/,''),group:'Загруженные файлы',fileName:file.name,note:text?text.slice(0,180):'Файл сохранён в реестре материалов проекта'};update({materials:[item,...project.materials],knowledge:text?[{title:item.title,icon:'▤',items:text.split(/\r?\n/).filter(Boolean).slice(0,18)},...project.knowledge]:project.knowledge});setSection(text?'База знаний':'Материалы');setMessage(`Готово: «${file.name}» добавлен в проект`)}catch(error){setMessage(`Не удалось загрузить «${file.name}»: ${error instanceof Error?error.message:'неизвестная ошибка'}`)}finally{setImporting(false);if(briefInput.current)briefInput.current.value=''}};
 const createProject=()=>{const name=projectName.trim();if(!name)return;const id=`project-${Date.now()}`;const next:Project={id,name,emoji:'◈',description:'Новый проект',tasks:[],knowledge:[],materials:[],comments:[]};setProjects(all=>[...all,next]);setProjectId(id);setProjectName('');setNewProject(false);setSection('Гант');setMessage('')};
 return <div className="app project-hub">
  {sidebar&&<aside><div className="brand"><div className="brandmark">B</div><span>Blink Hub</span><button className="icon close-side" onClick={()=>setSidebar(false)}><PanelLeftClose size={18}/></button></div><nav><p>ПРОЕКТЫ</p>{projects.map(item=><button className={'nav '+(item.id===project.id?'active':'')} onClick={()=>{setProjectId(item.id);setSection('Гант');setMessage('')}} key={item.id}><span className="project-emoji">{item.emoji}</span>{item.name}<span>{item.tasks.length}</span></button>)}<button className="nav add-project" onClick={()=>setNewProject(true)}><Plus/>Добавить проект</button></nav><div className="filters"><div className="filter-title">РАЗДЕЛЫ <ListFilter size={14}/></div>{(['Гант','База знаний','Материалы'] as const).map(name=><button key={name} className={'nav '+(section===name?'active':'')} onClick={()=>setSection(name)}>{name==='Гант'?<LayoutDashboard/>:name==='База знаний'?<BookOpen/>:<FolderOpen/>}{name}</button>)}</div><div className="project-card"><div><Sparkles size={18}/><b>{project.name}</b></div><strong>{project.tasks.length}</strong><small>задач · {project.materials.length} материалов</small></div><button className="profile"><span>СБ</span><div><b>Света Белоусова</b><small>Администратор</small></div><MoreHorizontal/></button></aside>}
  <main>{!sidebar&&<button className="open-side" onClick={()=>setSidebar(true)}>B</button>}<header><div><div className="crumb">Проекты <b>/</b> {project.name} <b>/</b> {section}</div><h1>{project.emoji} {project.name}</h1><p>{project.description}</p></div><div className="header-actions"><button className="icon"><Bell size={20}/></button><button onClick={()=>briefInput.current?.click()}><FileText/> Добавить вводные</button><button className="primary" onClick={()=>ganttInput.current?.click()}><UploadCloud/> Загрузить Гант</button><input ref={ganttInput} type="file" hidden accept=".xlsx,.xls,.csv,.json" onChange={e=>importGantt(e.target.files?.[0])}/><input ref={briefInput} type="file" hidden accept=".docx,.pdf,.txt,.md,.csv,.json,.pptx" onChange={e=>importBrief(e.target.files?.[0])}/></div></header>
   {message&&<div className={'notice '+(message.includes('Не ')||message.includes('найден')?'error':'')}><Check/> {message}</div>}
   {section==='Гант'&&<Gantt project={project} filtered={filtered} query={query} setQuery={setQuery} importing={importing} importFile={importGantt} openTask={setActive}/>}
   {section==='База знаний'&&<KnowledgeView project={project} addBrief={()=>briefInput.current?.click()}/>}
   {section==='Материалы'&&<MaterialsView project={project} addBrief={()=>briefInput.current?.click()}/>}
  </main>
  {newProject&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setNewProject(false)}><div className="project-modal"><button className="modal-close" onClick={()=>setNewProject(false)}><X/></button><div className="modal-symbol">◈</div><h2>Новый проект</h2><p>Создайте рабочее пространство, затем загрузите Гант и вводные.</p><label>Название проекта<input autoFocus value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="Например, Осенний запуск" onKeyDown={e=>e.key==='Enter'&&createProject()}/></label><button className="create-project" onClick={createProject}>Создать проект</button></div></div>}
  {active&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setActive(null)}><div className="task-modal"><button className="modal-close" onClick={()=>setActive(null)}><X/></button><span className="status-chip">{active.status}</span><h2>{active.title}</h2><p>{active.stage} · {active.owner}</p><div className="task-fields"><span>Прогресс <b>{active.progress}%</b></span><span>Длительность <b>{active.span} дн.</b></span><span>Старт <b>день {active.start+1}</b></span></div></div></div>}
 </div>
}

function Gantt({project,filtered,query,setQuery,importing,importFile,openTask}:{project:Project;filtered:Task[];query:string;setQuery:(x:string)=>void;importing:boolean;importFile:(f?:File)=>void;openTask:(t:Task)=>void}){return <><section className="import-panel" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();importFile(e.dataTransfer.files?.[0])}}><div className="import-icon"><UploadCloud/></div><div><b>{project.tasks.length?'Обновить диаграмму Ганта':'Добавить диаграмму Ганта'}</b><p>Перетащите Excel, CSV или JSON — задачи появятся на таймлайне.</p></div><label className="file-button">{importing?'Читаю файл…':'Выбрать файл'}<input type="file" accept=".xlsx,.xls,.csv,.json" onChange={e=>{const file=e.target.files?.[0];e.target.value='';importFile(file)}}/></label></section><section className="stats"><Stat label="Всего задач" value={project.tasks.length}/><Stat label="В работе" value={project.tasks.filter(t=>t.status==='В работе').length}/><Stat label="Выполнено" value={project.tasks.filter(t=>t.status==='Готово').length}/><Stat label="Материалы" value={project.materials.length}/></section><section className="workspace"><div className="toolbar"><div className="views"><button className="selected">Гант</button><button>Канбан</button><button>Список</button></div><div className="tools"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти задачу..."/></div><button><SlidersHorizontal/> Фильтры</button><button>Неделя <ChevronDown/></button></div></div>{project.tasks.length?<div className="gantt"><div className="gantt-head"><div className="task-col"><span>ЗАДАЧА</span><span>СТАТУС</span></div><div className="dates">{days.map((x,i)=><div className={i%7>4?'weekend':''} key={i}><b>{x.d}</b><small>{x.w}</small></div>)}</div></div><div className="rows">{filtered.map(t=><div className="row" key={t.id}><button className="task-info" onClick={()=>openTask(t)}><i style={{background:t.color}}/><div className="avatar" style={{background:t.color+'22',color:t.color}}>{t.initials}</div><div><b>{t.title}</b><small>{t.stage} · {t.owner}</small></div><span className={'status '+t.status.replace(' ','-').toLowerCase()}>{t.status}</span></button><div className="timeline">{days.map((_,i)=><i className={i%7>4?'weekend':''} key={i}/>)}<button className="bar" onClick={()=>openTask(t)} style={{left:`calc(${t.start} * 100% / 23 + 5px)`,width:`calc(${t.span} * 100% / 23 - 10px)`,background:t.color}}><span>{t.title}</span><b>{t.initials}</b></button></div></div>)}</div></div>:<Empty icon="▦" title="Гант пока не загружен" text="Загрузите XLSX, XLS, CSV или JSON, чтобы построить план проекта."/>}</section></>}
function KnowledgeView({project,addBrief}:{project:Project;addBrief:()=>void}){return <section className="knowledge-page"><div className="section-intro"><div><span className="eyebrow">ЕДИНОЕ ПРОСТРАНСТВО</span><h2>База знаний</h2><p>Механика, требования, QA и технические вводные проекта.</p></div><button onClick={addBrief}><Plus/>Добавить документ</button></div>{project.knowledge.length?<div className="knowledge-grid">{project.knowledge.map((card,i)=><article className="knowledge-card" key={card.title}><div className="knowledge-icon">{card.icon}</div><div><small>РАЗДЕЛ {String(i+1).padStart(2,'0')}</small><h3>{card.title}</h3><ul>{card.items.map(item=><li key={item}>{item}</li>)}</ul></div></article>)}</div>:<Empty icon="▤" title="База знаний пуста" text="Добавьте DOCX, PDF, TXT, Markdown или JSON с вводными проекта." action={addBrief}/>} {project.comments.length>0&&<div className="comments-section"><div className="section-intro"><div><span className="eyebrow">ИЗ ИСХОДНОГО ДОКУМЕНТА</span><h2>Комментарии</h2></div></div><div className="comment-grid">{project.comments.map((comment,i)=><article key={i}><div><MessageCircle/><b>{comment.author}</b></div><p>{comment.text}</p><small>К фрагменту: «{comment.anchor}»</small></article>)}</div></div>}</section>}
function MaterialsView({project,addBrief}:{project:Project;addBrief:()=>void}){return <section className="materials-page"><div className="section-intro"><div><span className="eyebrow">ФАЙЛЫ И ССЫЛКИ</span><h2>Материалы проекта</h2><p>Figma, формы, презентации, исходники и загруженные вводные.</p></div><button onClick={addBrief}><Plus/>Добавить файл</button></div>{project.materials.length?<div className="materials-grid">{project.materials.map((item,i)=>item.url?<a href={item.url} target="_blank" rel="noreferrer" className="material-card" key={item.title+i}><div className="material-icon">{item.group==='Figma'?'F':item.group==='Формы'?'▤':item.group==='Файлы'?'⬡':'↗'}</div><div><small>{item.group}</small><h3>{item.title}</h3><p>{item.note}</p></div><ArrowUpRight/></a>:<article className="material-card" key={item.title+i}><div className="material-icon"><File/></div><div><small>{item.group}</small><h3>{item.title}</h3><p>{item.note}</p></div></article>)}</div>:<Empty icon="◇" title="Материалов пока нет" text="Добавьте документы, таблицы, презентации или ссылки проекта." action={addBrief}/>}</section>}
function Stat({label,value}:{label:string;value:number}){return <div className="stat compact"><div><small>{label}</small><strong>{value}</strong><p>в текущем проекте</p></div></div>}
function Empty({icon,title,text,action}:{icon:string;title:string;text:string;action?:()=>void}){return <div className="empty-state"><div>{icon}</div><h2>{title}</h2><p>{text}</p>{action&&<button onClick={action}>Добавить файл</button>}</div>}
